---
abstract: 'manage directory and symlink creation, globally and per-project'
author:
  - 'John SJ Anderson <genehack@genehack.org>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-MiseEnPlace
recommends:
  IO::Page: 0
requires:
  App::Cmd::Simple: 0
  Carp: 0
  File::Basename: 0
  File::Path: 2.08
  File::Path::Expand: 0
  FindBin: 0
  Mouse: 0
  MouseX::NativeTraits: 1.04
  Term::ANSIColor: 0
  Try::Tiny: 0
  YAML: 0
  autodie: 0
  base: 0
  lib: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=App-MiseEnPlace
  homepage: http://search.cpan.org/dist/App-MiseEnPlace/
  repository: git://github.com/genehack/app-miseenplace.git
version: 0.15
x_Dist_Zilla:
  perl:
    version: 5.018000
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@GENEHACK/@Git/Check'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@GENEHACK/@Git/Commit'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@GENEHACK/@Git/Tag'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@GENEHACK/@Git/Push'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@GENEHACK/Git::NextVersion'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@GENEHACK/@Basic/GatherDir'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@GENEHACK/@Basic/PruneCruft'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@GENEHACK/@Basic/ManifestSkip'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@GENEHACK/@Basic/MetaYAML'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::License
      name: '@GENEHACK/@Basic/License'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@GENEHACK/@Basic/Readme'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@GENEHACK/@Basic/ExtraTests'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@GENEHACK/@Basic/ExecDir'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@GENEHACK/@Basic/ShareDir'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@GENEHACK/@Basic/MakeMaker'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@GENEHACK/@Basic/Manifest'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@GENEHACK/@Basic/TestRelease'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@GENEHACK/@Basic/ConfirmRelease'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@GENEHACK/@Basic/UploadToCPAN'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@GENEHACK/AutoPrereqs'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@GENEHACK/CheckChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@GENEHACK/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@GENEHACK/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@GENEHACK/PkgVersion'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
      name: '@GENEHACK/PodWeaver'
      version: 3.102000
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@GENEHACK/Bugtracker'
      version: 1.111080
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@GENEHACK/Homepage'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@GENEHACK/MetaConfig'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@GENEHACK/MetaJSON'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@GENEHACK/Repository'
      version: 0.19
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@GENEHACK/InstallGuide'
      version: 1.200001
    -
      class: Dist::Zilla::Plugin::ReadmeMarkdownFromPod
      name: '@GENEHACK/ReadmeMarkdownFromPod'
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@GENEHACK/CopyFilesFromBuild'
      version: 0.103510
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@GENEHACK/NextRelease'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@GENEHACK/ExtraTests'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@GENEHACK/PodCoverageTests'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@GENEHACK/PodSyntaxTests'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@GENEHACK/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@GENEHACK/Test::Compile'
      version: 2.033
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@GENEHACK/Twitter'
      version: 0.022
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@GENEHACK/Git::Commit'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@GENEHACK/Git::Tag'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@GENEHACK/InstallRelease'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: '@GENEHACK/ArchiveRelease'
      version: 4.00
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: recommends
      name: RuntimeRecommends
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300039
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300039
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300039
x_authority: cpan:GENEHACK
